// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Whether the calling window has a native glass background. */
	windowGlass: () => __TAURI_INVOKE<boolean>("window_glass"),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	updateSettings: (settings: Settings) => typedError<SettingsUpdate, string>(__TAURI_INVOKE("update_settings", { settings })),
	setPaused: (paused: boolean) => __TAURI_INVOKE<void>("set_paused", { paused }),
	providerKinds: () => __TAURI_INVOKE<ProviderKindInfo[]>("provider_kinds"),
	keyStatuses: () => __TAURI_INVOKE<KeyStatus[]>("key_statuses"),
	setApiKey: (providerId: string, key: string | null) => typedError<null, string>(__TAURI_INVOKE("set_api_key", { providerId, key })),
	listModels: (providerId: string) => typedError<string[], string>(__TAURI_INVOKE("list_models", { providerId })),
	testProvider: (providerId: string) => typedError<TranslationResult, string>(__TAURI_INVOKE("test_provider", { providerId })),
	translate: (request: TranslateRequest, requestId: string, origin: Origin, appExe: string | null, saveHistory: boolean, onEvent: Channel<TranslateEvent>) => typedError<TranslationResult, string>(__TAURI_INVOKE("translate", { request, requestId, origin, appExe, saveHistory, onEvent })),
	cancelTranslation: (requestId: string) => __TAURI_INVOKE<void>("cancel_translation", { requestId }),
	detectLanguage: (text: string) => __TAURI_INVOKE<string | null>("detect_language", { text }),
	historyList: (query: HistoryQuery) => typedError<HistoryItem[], string>(__TAURI_INVOKE("history_list", { query })),
	/**  Save a translation made in the main window (once the user stopped typing). */
	historyCommit: (sourceText: string, result: TranslationResult) => typedError<null, string>(__TAURI_INVOKE("history_commit", { sourceText, result })),
	historyToggleFavorite: (id: number) => typedError<null, string>(__TAURI_INVOKE("history_toggle_favorite", { id })),
	historyDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("history_delete", { id })),
	historyClear: (keepFavorites: boolean) => typedError<null, string>(__TAURI_INVOKE("history_clear", { keepFavorites })),
	usageStats: () => typedError<UsageStats, string>(__TAURI_INVOKE("usage_stats")),
	usageReset: () => typedError<null, string>(__TAURI_INVOKE("usage_reset")),
	cacheClear: () => typedError<null, string>(__TAURI_INVOKE("cache_clear")),
	popupTakePending: () => __TAURI_INVOKE<{
	id: number,
	text: string,
	context: string | null,
	origin: Origin,
	/**  Executable of the app the text came from. */
	app: string | null,
	/**  Start translating immediately. */
	translate: boolean,
	/**  The selection can be replaced with the translation. */
	can_replace: boolean,
	/**  Message to show instead of a translation (e.g. "nothing selected"). */
	notice: string | null,
} | null>("popup_take_pending"),
	popupSetPinned: (pinned: boolean) => __TAURI_INVOKE<void>("popup_set_pinned", { pinned }),
	popupHide: () => __TAURI_INVOKE<void>("popup_hide"),
	openInMain: (text: string) => __TAURI_INVOKE<void>("open_in_main", { text }),
	/**  Replace the selection in the app the popup was opened from. */
	replaceWith: (text: string) => typedError<null, string>(__TAURI_INVOKE("replace_with", { text })),
	copyText: (text: string) => typedError<null, string>(__TAURI_INVOKE("copy_text", { text })),
	excludeApp: (exe: string) => typedError<null, string>(__TAURI_INVOKE("exclude_app", { exe })),
	iconClicked: () => __TAURI_INVOKE<void>("icon_clicked"),
	regionInit: () => __TAURI_INVOKE<{
	index: number,
	url: string,
	scale_factor: number | null,
} | null>("region_init"),
	regionReady: (index: number) => __TAURI_INVOKE<void>("region_ready", { index }),
	regionSelected: (index: number, rect: RegionRect) => __TAURI_INVOKE<void>("region_selected", { index, rect }),
	regionCancel: () => __TAURI_INVOKE<void>("region_cancel"),
	startOcr: () => __TAURI_INVOKE<void>("start_ocr"),
	openMain: (view: string | null) => __TAURI_INVOKE<void>("open_main", { view }),
	quit: () => __TAURI_INVOKE<void>("quit"),
	updateStatus: () => __TAURI_INVOKE<UpdateStatus>("update_status"),
	/**  Check now (and download if there is a newer version). */
	checkUpdates: () => __TAURI_INVOKE<UpdateStatus>("check_updates"),
	/**  Install the downloaded update right away and start the new version. */
	restartToUpdate: () => __TAURI_INVOKE<boolean>("restart_to_update"),
};

/** Events */
export const events = {
	historyChanged: makeEvent<HistoryChanged>("history-changed"),
	iconBusy: makeEvent<IconBusy>("icon-busy"),
	mainNavigate: makeEvent<MainNavigate>("main-navigate"),
	mainOpenText: makeEvent<MainOpenText>("main-open-text"),
	popupHidden: makeEvent<PopupHidden>("popup-hidden"),
	popupShow: makeEvent<PopupShow>("popup-show"),
	regionShow: makeEvent<RegionShow>("region-show"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	updateStatus: makeEvent<UpdateStatus>("update-status"),
};

/* Types */
export type Anchor = 
/**  Near the selected text when its position is known, otherwise near the cursor. */
"selection" | "cursor";

export type AppInfo = {
	version: string,
	system_language: string,
	is_windows_11: boolean,
	ocr_languages: string[],
	accent_colors: string[],
	languages: string[],
};

/**  How the source language is detected when the user did not set it. */
export type DetectionMode = 
/**  Fast offline detector; LLM / provider decides only when it is unsure. */
"local" | 
/**  Always let the LLM decide (more accurate for short / mixed text). */
"llm";

export type DictionaryEntry = {
	word: string,
	lemma?: string | null,
	transcription?: string | null,
	senses?: DictionarySense[],
	forms?: string | null,
	note?: string | null,
};

export type DictionaryExample = {
	source: string,
	target: string,
};

export type DictionarySense = {
	pos?: string | null,
	translations?: string[],
	meaning?: string | null,
	examples?: DictionaryExample[],
};

export type DoubleCopyDetection = 
/**  Watch clipboard changes while Ctrl is held. No keyboard hook. */
"clipboard" | 
/**  Low-level keyboard hook. */
"keyboard";

export type Formality = "default" | "formal" | "informal";

export type GeneralSettings = {
	/**  "system" or a UI language code (ru / en / es). */
	ui_language?: string,
	theme?: ThemeMode,
	window_effect?: WindowEffect,
	autostart?: boolean,
	/**  Open the main window when the app starts (otherwise only the tray icon). */
	show_main_on_start?: boolean,
	/**  Closing the main window keeps the app running in the tray. */
	close_to_tray?: boolean,
	/**  Download updates in the background and install them on exit. */
	auto_update?: boolean,
	/**  Interface zoom, percent. */
	ui_scale?: number,
	/**  Font size of source / translated text, px (at 100% zoom). */
	font_size?: number,
};

export type HistoryChanged = null;

export type HistoryItem = {
	id: number,
	/**  Unix time, ms. */
	created_at: number | null,
	source_text: string,
	result_text: string,
	dictionary: DictionaryEntry | null,
	source_lang: string | null,
	target_lang: string,
	provider_name: string,
	model: string | null,
	cost_usd: number | null,
	origin: Origin,
	app: string | null,
	favorite: boolean,
};

export type HistoryQuery = {
	search: string | null,
	favorites_only: boolean,
	limit: number,
	offset: number,
};

export type HotkeySettings = {
	/**  Accelerators in global-hotkey format, e.g. "Ctrl+Alt+KeyT". Empty = disabled. */
	translate_selection?: string,
	replace_selection?: string,
	ocr_region?: string,
	translate_clipboard?: string,
	open_main?: string,
};

export type IconBusy = boolean;

export type KeyStatus = {
	id: string,
	hint: string | null,
};

export type LanguageSettings = {
	/**  Text in any other language is translated into this one. */
	primary?: string,
	/**  Text already in `primary` is translated into this one. */
	secondary?: string,
	/**  Shown first in language pickers and used to disambiguate detection. */
	favorites?: string[],
	detection?: DetectionMode,
};

/**  Switch the main window to a view ("translate" | "history" | "settings"). */
export type MainNavigate = string;

/**  Put text into the main window's source field. */
export type MainOpenText = {
	text: string,
	translate: boolean,
};

/**  Why a model is suggested; shown as a label in the model picker. */
export type ModelTier = 
/**  Best balance of quality, speed and price for translation. */
"recommended" | "fast" | "quality";

export type OcrSettings = {
	/**  BCP-47 tag of a Windows OCR language, or "auto". */
	language?: string,
	/**  Translate right away (otherwise only show the recognized text). */
	translate?: boolean,
};

export type Origin = "main" | "selection" | "clipboard" | "ocr" | "replace";

export type OutputKind = "text" | "dictionary";

export type PopupHidden = null;

/**  What the popup should show. */
export type PopupPayload = {
	id: number,
	text: string,
	context: string | null,
	origin: Origin,
	/**  Executable of the app the text came from. */
	app: string | null,
	/**  Start translating immediately. */
	translate: boolean,
	/**  The selection can be replaced with the translation. */
	can_replace: boolean,
	/**  Message to show instead of a translation (e.g. "nothing selected"). */
	notice: string | null,
};

export type PopupPlacement = "selection" | "cursor" | 
/**  Where the pinned popup was last left. */
"last_position" | "screen_center";

export type PopupSettings = {
	placement?: PopupPlacement,
	close_on_blur?: boolean,
	/**  Every popup opens pinned. */
	always_pinned?: boolean,
	width?: number,
	height?: number,
	/**  Logical position of the pinned popup. */
	last_x?: number | null,
	last_y?: number | null,
};

/**  The popup has new content. */
export type PopupShow = PopupPayload;

export type ProviderConfig = {
	id: string,
	kind: ProviderKind,
	name: string,
	enabled: boolean,
	base_url?: string | null,
	model?: string | null,
	/**  Azure region for Microsoft Translator. */
	region?: string | null,
	temperature?: number | null,
	/**  Extra JSON merged into the chat-completions body (LLM providers). */
	extra_body?: string | null,
	/**  LLM: $ per 1M input tokens. Character APIs: $ per 1M characters. */
	price_input?: number | null,
	/**  LLM: $ per 1M output tokens. */
	price_output?: number | null,
};

export type ProviderKind = "groq" | "open_ai" | "open_router" | "gemini" | "anthropic" | "ollama" | "lm_studio" | 
/**  Any other OpenAI-compatible endpoint. */
"open_ai_compatible" | "deepl" | "google_cloud" | 
/**  Unofficial free Google endpoint, no key needed. */
"google_free" | "microsoft";

export type ProviderKindInfo = {
	kind: ProviderKind,
	label: string,
	is_llm: boolean,
	needs_key: boolean,
	default_base_url: string | null,
	default_model: string | null,
	recommended_models: RecommendedModel[],
};

export type RecommendedModel = {
	id: string,
	tier: ModelTier,
};

export type RegionRect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  A region-picker window should display a frozen screenshot. */
export type RegionShow = {
	index: number,
	url: string,
	scale_factor: number | null,
};

/**  How the selected text is read from other applications. */
export type SelectionMethod = 
/**  Accessibility API only. Never touches the clipboard. */
"uia" | 
/**  Simulate Ctrl+C and restore the clipboard afterwards. */
"clipboard" | 
/**  Accessibility API first, clipboard when it returns nothing. */
"uia_then_clipboard";

export type SelectionSettings = {
	/**  How the hotkey reads selected text. */
	method?: SelectionMethod,
	/**  Put the previous clipboard content back after reading the selection via Ctrl+C. */
	restore_clipboard?: boolean,
	/**  Show a floating button after selecting text with the mouse. */
	icon_enabled?: boolean,
	icon_anchor?: Anchor,
	/**  Hide the button after this many ms (0 = until the next click). */
	icon_timeout_ms?: number,
	/**
	 *  The button may also read the selection via Ctrl+C when UI Automation fails.
	 *  Off by default: it would touch the clipboard after every mouse selection.
	 */
	icon_clipboard_fallback?: boolean,
	/**  Ctrl+C+C translates the copied text. */
	double_copy_enabled?: boolean,
	double_copy_detection?: DoubleCopyDetection,
	double_copy_interval_ms?: number,
	/**  Executables (e.g. "code.exe") where automatic triggers are disabled. */
	excluded_apps?: string[],
};

export type Settings = {
	version?: number,
	general?: GeneralSettings,
	languages?: LanguageSettings,
	/**  Fallback chain: enabled providers are tried in this order. */
	providers?: ProviderConfig[],
	translation?: TranslationSettings,
	selection?: SelectionSettings,
	hotkeys?: HotkeySettings,
	popup?: PopupSettings,
	ocr?: OcrSettings,
	/**  Automatic triggers (button, Ctrl+C+C) are paused from the tray. */
	paused?: boolean,
};

export type SettingsChanged = Settings;

export type SettingsUpdate = {
	settings: Settings,
	warnings: string[],
};

export type ThemeMode = "system" | "light" | "dark";

/**  Streamed to the UI while a translation is running. */
export type TranslateEvent = { type: "started"; provider_id: string; provider_name: string; model: string | null; source_lang: string | null; target_lang: string | null; kind: OutputKind } | 
/**  Direction became known while streaming (LLM decided it). */
{ type: "direction"; source_lang: string | null; target_lang: string } | { type: "delta"; text: string } | 
/**  The provider failed in the middle; text shown so far must be dropped. */
{ type: "reset"; reason: string } | { type: "done"; result: TranslationResult } | { type: "error"; message: string };

/**  What the user wants to get back. */
export type TranslateMode = 
/**  Dictionary card for a single word (if enabled in options), translation otherwise. */
"auto" | "translate" | "dictionary";

export type TranslateRequest = {
	text: string,
	/**  `None` = detect automatically. */
	source_lang: string | null,
	/**  `None` = automatic direction using the language pair. */
	target_lang: string | null,
	mode?: TranslateMode,
	/**  Surrounding text / app info that helps the LLM; never translated itself. */
	context: string | null,
	formality?: Formality,
	/**  Use only this provider (otherwise the configured fallback chain). */
	provider_id: string | null,
};

export type TranslationResult = {
	text: string,
	source_lang: string | null,
	target_lang: string,
	provider_id: string,
	provider_name: string,
	model: string | null,
	usage: Usage,
	cost_usd: number | null,
	kind: OutputKind,
	dictionary: DictionaryEntry | null,
	cached: boolean,
	elapsed_ms: number,
};

export type TranslationSettings = {
	formality?: Formality,
	/**  Extra instructions for LLM providers (style, terminology). */
	custom_instructions?: string,
	/**  Show a dictionary card for single words (LLM providers). */
	dictionary_for_words?: boolean,
	/**  Send surrounding text of the selection to the LLM for better accuracy. */
	use_context?: boolean,
	cache?: boolean,
	history?: boolean,
	history_limit?: number,
};

export type UpdatePhase = "idle" | "checking" | "downloading" | 
/**  Downloaded; will be installed when the app exits. */
"ready" | "up_to_date" | "error";

export type UpdateStatus = {
	current: string,
	latest: string | null,
	phase: UpdatePhase,
	error: string | null,
	/**  Unix ms of the last finished check. */
	checked_at: number | null,
};

export type Usage = {
	input_tokens: number,
	output_tokens: number,
	/**  Characters sent to a character-billed provider (DeepL, Google, Microsoft). */
	characters: number,
};

export type UsageRow = {
	provider_id: string,
	provider_name: string,
	requests: number,
	input_tokens: number | null,
	output_tokens: number | null,
	characters: number | null,
	cost_usd: number | null,
};

export type UsageStats = {
	today: UsageRow[],
	month: UsageRow[],
	total: UsageRow[],
};

export type WindowEffect = 
/**  Mica / Acrylic on Windows 11, solid translucent background elsewhere. */
"auto" | "mica" | "acrylic" | "none";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

